# Generated by Django 5.2 on 2025-04-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=128)),
                ("cuisine", models.CharField(max_length=50)),
                ("URL", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "meal_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FoodStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("storage_time", models.IntegerField(blank=True, null=True)),
                ("method", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "food_storage",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Geospatial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("type", models.CharField(max_length=100)),
                ("hours_of_operation", models.TextField()),
                ("address", models.TextField()),
            ],
            options={
                "db_table": "geospatial",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SecondLife",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("items", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("picture", models.URLField(max_length=255)),
                ("inside_picture", models.URLField(max_length=255)),
            ],
            options={
                "db_table": "diy_projects",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FoodIngredient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("dish", models.CharField(max_length=255)),
                ("ingredient", models.TextField()),
            ],
            options={
                "db_table": "food_ingredients",
                "managed": True,
            },
        ),
    ]
