
# Generated by Django 5.2 on 2025-04-29 12:22


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='secondlife',
            table='diy_products',
        ),
    ]
