# Generated by Django 5.1.7 on 2025-04-06 03:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendar_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('expiry_date', models.DateField()),
                ('reminder_date', models.DateTimeField()),
                ('reminder_days', models.IntegerField(default=2)),
                ('reminder_time', models.CharField(default='20:00', max_length=5)),
            ],
            options={
                'indexes': [models.Index(fields=['calendar_id'], name='api_foodite_calenda_0e7c26_idx')],
            },
        ),
    ]
