# Generated by Django 5.1.7 on 2025-04-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_fooditem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Temperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("day", models.IntegerField()),
                ("temperature", models.FloatField()),
            ],
            options={
                "db_table": "temperature",
                "managed": False,
            },
        ),
    ]
