# Generated by Django 5.2 on 2025-04-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_foodstorage_geospatial_delete_user_and_more"),
        ("api", "0004_remove_fooditem"),
    ]

    operations = []
