# Generated by Django 5.2 on 2025-04-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_merge_20250427_0837"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=128)),
                ("cuisine", models.CharField(max_length=50)),
                ("URL", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "meal_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SecondLife",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("items", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("picture", models.URLField(max_length=255)),
                ("inside_picture", models.URLField(max_length=255)),
            ],
            options={
                "db_table": "diy_projects",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FoodIngredient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("dish", models.CharField(max_length=255)),
                ("ingredient", models.TextField()),
            ],
            options={
                "db_table": "food_ingredients",
                "managed": True,
            },
        ),
    ]
