version: '3.8'

networks:
  bestbefore-network:
    driver: bridge

services:
  backend-iteration1:
    build:
      context: ./backend
    container_name: backend-iteration1
    networks:
      - bestbefore-network
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    restart: unless-stopped

  frontend-iteration1:
    build:
      context: ./frontend
    container_name: frontend-iteration1
    networks:
      - bestbefore-network
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    networks:
      - bestbefore-network
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend-iteration1
      - frontend-iteration1
    restart: unless-stopped 